name: Test

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        paths:
            - "backend/**"
            - ".github/workflows/test.yaml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

env:
    BACKEND_DIR: "backend"

jobs:
    go-test:
        name: go test
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.BACKEND_DIR }}
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Set up backend
              uses: ./.github/actions/setup-backend
            
            - name: Run go test
              run: go test -race -cover -shuffle=on ./...
